# Lista de Exercícios: NumPy

## Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1 

In [2]:
#Importe a biblioteca NumPy para seu Notebook
import numpy as np

### Exercício 2

In [8]:
#Compare a velocidade, da operação a seguir, entre uma lista de Python Puro e um ndarray do NumPy com 1 bilhão de elementos
my_arr=np.arange(10000000)
my_list=list(range(10000000))



In [9]:
#Eleve a potência quadrática cada elemento do ndarray e da lista e exiba o tempo de execução de cada um dos objetos

%time for _ in range(10): my_arr2=my_arr*2

Wall time: 369 ms


In [10]:
%time for _ in range(10): my_list2=[x*2 for x in my_list]

Wall time: 13.2 s


### Exercício 3

In [81]:
#Crie uma matriz de cinco linhas e três colunas
data=np.random.randn(5,3)

print(data)

[[ 0.29872197 -0.0476794  -1.42665675]
 [ 0.26419274  1.27780249  0.89225142]
 [-0.08160859  0.37124315 -0.59398409]
 [-0.3169619  -0.4769215   0.66871708]
 [ 0.52663727 -0.0462788  -0.16255901]]


In [82]:
#Calcule a Raiz Quadrada dos elementos da matriz de uma única vez

print(np.sqrt(data))

[[0.54655463        nan        nan]
 [0.51399683 1.13039926 0.94459061]
 [       nan 0.60929726        nan]
 [       nan        nan 0.81775123]
 [0.72569778        nan        nan]]


C:\Users\aluno.laboratorio\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


### Exercício 4

In [83]:
#Crie as matrizes a seguir e verifique suas propriedades (formato, tipo e número de dimensões)
import numpy as np
matriz1 = np.random.rand(8, 5)
print("matriz1 \nFormato " + str(matriz1.shape), "Tipo " + str(matriz1.dtype), "Nº de Dimensões " + str(matriz1.ndim))

matriz2 = np.array([[7., 8, 9, 10.98], [65, 42, 3, 18]])
print("matriz2 \nFormato " + str(matriz2.shape), "Tipo " + str(matriz2.dtype), "Nº de Dimensões " + str(matriz2.ndim))

matriz3 = np.array([[1, "2", "4.5", 7], [4, "18", 14, "3"]], dtype=np.string_)
print("matriz3 \nFormato " + str(matriz3.shape), "Tipo " + str(matriz3.dtype), "Nº de Dimensões " + str(matriz3.ndim))

matriz1 
Formato (8, 5) Tipo float64 Nº de Dimensões 2
matriz2 
Formato (2, 4) Tipo float64 Nº de Dimensões 2
matriz3 
Formato (2, 4) Tipo |S3 Nº de Dimensões 2


### Exercício 5

In [86]:
#Crie uma ndarray de 3x4 do tipo float e converta para:
#(1) int
#(2) string
float_arr = np.random.randn(12).reshape(3, 4,)
print(float_arr)
int_arr = float_arr.astype(np.int32)
print(int_arr)
str_arr = float_arr.astype(np.string_)
print(str_arr)

[[-0.17267144  0.70654591  1.03126481  0.47410006]
 [-0.59516748 -0.70849251  1.21228318 -0.6437319 ]
 [ 0.42243981  1.70733952 -0.6039401   0.93047402]]
[[0 0 1 0]
 [0 0 1 0]
 [0 1 0 0]]
[[b'-0.1726714390816246' b'0.7065459130534023' b'1.0312648111520484'
  b'0.47410005842890474']
 [b'-0.5951674849530589' b'-0.7084925136820778' b'1.2122831828044978'
  b'-0.6437319028693266']
 [b'0.4224398076133064' b'1.7073395198332724' b'-0.6039400967051574'
  b'0.9304740211055141']]


### Exercício 6

In [88]:
#Crie um ndarray com 100 números aleatórios
data2 = np.random.randn(100)

In [89]:
data2

array([-1.1338497 ,  0.07248928,  1.05942495, -0.0818828 , -0.05151791,
       -0.47354894,  0.81651964, -0.87271241,  1.27003105,  1.47674352,
        0.70203612,  1.13983137, -0.41972492,  1.8111986 ,  0.20579697,
       -0.91180738,  1.52900319, -0.10857089, -1.0355823 ,  0.05418635,
        0.55674358,  2.15211502,  0.66259247, -1.88697146, -0.08483254,
       -0.61673567, -0.04411036,  0.83751499,  0.24801053, -0.43258345,
        1.31590763,  0.04333612, -1.22614277,  0.18680703,  0.36067268,
       -0.94999634,  1.03675775, -0.95748497,  0.03853381,  0.98995242,
       -0.49206998, -0.14899198, -2.1405236 ,  0.86360274,  0.25421554,
        1.16627032, -0.90241332, -0.1742851 , -0.66230861, -0.33608103,
        0.0456636 , -2.30821086,  0.28912406,  2.05849755, -0.15180502,
        0.7512387 ,  0.23642154, -0.77720542, -1.46646017,  0.25022734,
        0.87050548,  0.90382002,  0.56491435,  2.33632319,  1.37379492,
        0.63577836, -0.08705916,  1.1100376 , -0.06593932, -1.39

In [90]:
#Acesse o 32º elemento
data2[31]

0.04333612247496501

In [93]:
#Altere os índices de 18 a 32 para 128
data2[18:33]=128

In [92]:
data2

array([-1.13384970e+00,  7.24892750e-02,  1.05942495e+00, -8.18828036e-02,
       -5.15179147e-02, -4.73548938e-01,  8.16519637e-01, -8.72712409e-01,
        1.27003105e+00,  1.47674352e+00,  7.02036123e-01,  1.13983137e+00,
       -4.19724924e-01,  1.81119860e+00,  2.05796973e-01, -9.11807376e-01,
        1.52900319e+00, -1.08570887e-01,  1.28000000e+02,  1.28000000e+02,
        1.28000000e+02,  1.28000000e+02,  1.28000000e+02,  1.28000000e+02,
        1.28000000e+02,  1.28000000e+02,  1.28000000e+02,  1.28000000e+02,
        1.28000000e+02,  1.28000000e+02,  1.28000000e+02,  1.28000000e+02,
       -1.22614277e+00,  1.86807032e-01,  3.60672680e-01, -9.49996341e-01,
        1.03675775e+00, -9.57484967e-01,  3.85338056e-02,  9.89952423e-01,
       -4.92069979e-01, -1.48991978e-01, -2.14052360e+00,  8.63602737e-01,
        2.54215537e-01,  1.16627032e+00, -9.02413321e-01, -1.74285104e-01,
       -6.62308611e-01, -3.36081033e-01,  4.56635971e-02, -2.30821086e+00,
        2.89124060e-01,  

In [94]:
#Copie o ndarray para um novo ndarray
data3 = data2.copy()

In [95]:
data3

array([-1.13384970e+00,  7.24892750e-02,  1.05942495e+00, -8.18828036e-02,
       -5.15179147e-02, -4.73548938e-01,  8.16519637e-01, -8.72712409e-01,
        1.27003105e+00,  1.47674352e+00,  7.02036123e-01,  1.13983137e+00,
       -4.19724924e-01,  1.81119860e+00,  2.05796973e-01, -9.11807376e-01,
        1.52900319e+00, -1.08570887e-01,  1.28000000e+02,  1.28000000e+02,
        1.28000000e+02,  1.28000000e+02,  1.28000000e+02,  1.28000000e+02,
        1.28000000e+02,  1.28000000e+02,  1.28000000e+02,  1.28000000e+02,
        1.28000000e+02,  1.28000000e+02,  1.28000000e+02,  1.28000000e+02,
        1.28000000e+02,  1.86807032e-01,  3.60672680e-01, -9.49996341e-01,
        1.03675775e+00, -9.57484967e-01,  3.85338056e-02,  9.89952423e-01,
       -4.92069979e-01, -1.48991978e-01, -2.14052360e+00,  8.63602737e-01,
        2.54215537e-01,  1.16627032e+00, -9.02413321e-01, -1.74285104e-01,
       -6.62308611e-01, -3.36081033e-01,  4.56635971e-02, -2.30821086e+00,
        2.89124060e-01,  

In [96]:
#Exiba o primeiro ndarray
data2

array([-1.13384970e+00,  7.24892750e-02,  1.05942495e+00, -8.18828036e-02,
       -5.15179147e-02, -4.73548938e-01,  8.16519637e-01, -8.72712409e-01,
        1.27003105e+00,  1.47674352e+00,  7.02036123e-01,  1.13983137e+00,
       -4.19724924e-01,  1.81119860e+00,  2.05796973e-01, -9.11807376e-01,
        1.52900319e+00, -1.08570887e-01,  1.28000000e+02,  1.28000000e+02,
        1.28000000e+02,  1.28000000e+02,  1.28000000e+02,  1.28000000e+02,
        1.28000000e+02,  1.28000000e+02,  1.28000000e+02,  1.28000000e+02,
        1.28000000e+02,  1.28000000e+02,  1.28000000e+02,  1.28000000e+02,
        1.28000000e+02,  1.86807032e-01,  3.60672680e-01, -9.49996341e-01,
        1.03675775e+00, -9.57484967e-01,  3.85338056e-02,  9.89952423e-01,
       -4.92069979e-01, -1.48991978e-01, -2.14052360e+00,  8.63602737e-01,
        2.54215537e-01,  1.16627032e+00, -9.02413321e-01, -1.74285104e-01,
       -6.62308611e-01, -3.36081033e-01,  4.56635971e-02, -2.30821086e+00,
        2.89124060e-01,  

In [97]:
#Altere o segundo ndarray modificando os índices de 18 a 32 para 256
data3[18:33]=256

In [98]:
#Exiba o segundo ndarray
data3

array([-1.13384970e+00,  7.24892750e-02,  1.05942495e+00, -8.18828036e-02,
       -5.15179147e-02, -4.73548938e-01,  8.16519637e-01, -8.72712409e-01,
        1.27003105e+00,  1.47674352e+00,  7.02036123e-01,  1.13983137e+00,
       -4.19724924e-01,  1.81119860e+00,  2.05796973e-01, -9.11807376e-01,
        1.52900319e+00, -1.08570887e-01,  2.56000000e+02,  2.56000000e+02,
        2.56000000e+02,  2.56000000e+02,  2.56000000e+02,  2.56000000e+02,
        2.56000000e+02,  2.56000000e+02,  2.56000000e+02,  2.56000000e+02,
        2.56000000e+02,  2.56000000e+02,  2.56000000e+02,  2.56000000e+02,
        2.56000000e+02,  1.86807032e-01,  3.60672680e-01, -9.49996341e-01,
        1.03675775e+00, -9.57484967e-01,  3.85338056e-02,  9.89952423e-01,
       -4.92069979e-01, -1.48991978e-01, -2.14052360e+00,  8.63602737e-01,
        2.54215537e-01,  1.16627032e+00, -9.02413321e-01, -1.74285104e-01,
       -6.62308611e-01, -3.36081033e-01,  4.56635971e-02, -2.30821086e+00,
        2.89124060e-01,  

### Exercício 7

In [79]:
#Crie a matriz abaixo
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(arr2d)
#Selecione através dos índices os itens 5, 6 e 7
print(arr2d[1,:-1])
#Selecione através dos índices os itens 7, 11 e 15
print(arr2d[1:,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[5 6 7]
[ 7 11 15]


### Exercício 8

In [58]:
#Crie uma lista com os nomes: Antônio, Carlos, Carlos, Antônio, José, Alfredo, Alfredo, Antônio
nomes = np.array(['Antônio', 'Carlos', 'Carlos', 'Antônio', 'José', 'Alfredo', 'Alfredo', 'Antônio'])

In [60]:
#Crie uma lista chamada dívidas com os seguintes valores: 1000., 500., 0, 1640, 18399.99, 42640.18, 70., 84.90
dividas = np.array([1000., 500., 0, 1640, 18399.99, 42640.18, 70., 84.90])

In [61]:
#Busque na lista de nomes as ocorrências de Antônio e exiba suas dívidas
dividas[nomes=='Antônio']

array([1000. , 1640. ,   84.9])

In [62]:
#Busque na lista de nomes as ocorrências de José e exiba suas dívidas
dividas[nomes=='José']

array([18399.99])

In [99]:
#Exiba as dívidas das pessoas diferente de Antônio e José
nomes[(nomes != "Antônio") & (nomes != "José")]

array(['Alfredo', 'Alfredo', 'Carlos', 'Carlos'], dtype='<U7')

In [68]:
#Exiba os nomes das pessoas que possuem dívidas igual a 0 (zero)
nomes[dividas==0]

array(['Carlos'], dtype='<U7')

In [70]:
#Exiba os nomes das pessoas que possuem dívidas maior que 10000 (dez mil)
nomes[dividas>10000]


array(['José', 'Alfredo'], dtype='<U7')

In [100]:
#Exiba os nomes das pessoas que possuem dívidas menores que 100 (cem) e maior do que 0 (zero)
nomes[(dividas < 100) & (dividas > 0)]

array(['Carlos', 'José'], dtype='<U7')

### Exercício 9

In [75]:
#Ordene e exiba a lista de nomes criado no execício anterior
nomes.sort()
nomes

array(['Alfredo', 'Alfredo', 'Antônio', 'Antônio', 'Antônio', 'Carlos',
       'Carlos', 'José'], dtype='<U7')

In [102]:
#Ordene em ordem decrescente e exiba a lista de valores criado no execício anterior
dividas_ord = -np.sort(-dividas)
print(dividas)
print(dividas_ord)

[ 1000.     500.       0.    1640.   18399.99 42640.18    70.      84.9 ]
[42640.18 18399.99  1640.    1000.     500.      84.9     70.       0.  ]


### Exercício 10

In [77]:
#Exiba os valores únicos das listas criadas no exercício 8
print(np.unique(nomes))
print(np.unique(dividas))

['Alfredo' 'Antônio' 'Carlos' 'José']
[    0.      70.      84.9    500.    1000.    1640.   18399.99 42640.18]
