# Lista de Exercícios: NumPy

## Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1 

In [1]:
#Importe a biblioteca NumPy para seu Notebook
import numpy as np

### Exercício 2

In [2]:
#Compare a velocidade, da operação a seguir, entre uma lista de Python Puro e um ndarray do NumPy com 1 bilhão de elementos
#
#Eleve a potência quadrática cada elemento do ndarray e da lista e exiba o tempo de execução de cada um dos objetos
my_arr = np.arange(10000000)
my_list = list(range(10000000))

%time for _ in range(10): my_arr2 = my_arr ** 2

Wall time: 339 ms


In [3]:
%time for _ in range(10): my_list2 = [x* 2 for x in my_list]

Wall time: 11.9 s


### Exercício 3

In [4]:
#Crie uma matriz de cinco linhas e três colunas
#Calcule a Raiz Quadrada dos elementos da matriz de uma única vez
matriz = np.random.randn(5, 3)
print(matriz)
print(np.sqrt(matriz))

[[ 0.54311818  2.55762255 -0.57575271]
 [ 0.85769735 -0.83060941 -0.53480623]
 [-0.50695915  0.60671476  2.48857636]
 [ 0.44599541  1.77904671  1.31654788]
 [ 1.02410182 -1.98719645 -0.34982489]]
[[0.73696552 1.59925687        nan]
 [0.92611951        nan        nan]
 [       nan 0.77891897 1.57752222]
 [0.66782888 1.3338091  1.1474092 ]
 [1.01197916        nan        nan]]


C:\Users\aluno.laboratorio\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in sqrt
  """


### Exercício 4

In [5]:
#Crie as matrizes a seguir e verifique suas propriedades (formato, tipo e número de dimensões)
import numpy as np
matriz1 = np.random.rand(8, 5)
print("matriz1 \nFormato " + str(matriz1.shape), "Tipo " + str(matriz1.dtype), "Nº de Dimensões " + str(matriz1.ndim))

matriz2 = np.array([[7., 8, 9, 10.98], [65, 42, 3, 18]])
print("matriz2 \nFormato " + str(matriz2.shape), "Tipo " + str(matriz2.dtype), "Nº de Dimensões " + str(matriz2.ndim))

matriz3 = np.array([[1, "2", "4.5", 7], [4, "18", 14, "3"]], dtype=np.string_)
print("matriz3 \nFormato " + str(matriz3.shape), "Tipo " + str(matriz3.dtype), "Nº de Dimensões " + str(matriz3.ndim))

matriz1 
Formato (8, 5) Tipo float64 Nº de Dimensões 2
matriz2 
Formato (2, 4) Tipo float64 Nº de Dimensões 2
matriz3 
Formato (2, 4) Tipo |S3 Nº de Dimensões 2


### Exercício 5

In [6]:
#Crie uma ndarray de 3x4 do tipo float e converta para:
#(1) int
#(2) string
float_arr = np.random.randn(12).reshape(3, 4)
print(float_arr)
int_arr = float_arr.astype(np.int32)
print(int_arr)
str_arr = float_arr.astype(np.string_)
print(str_arr)

[[-0.24094334 -0.52877436  0.43893531 -0.86175908]
 [-0.23491262  1.09130086  0.95529578  0.3183988 ]
 [ 1.67003942  0.53521949  0.2310326   1.60069693]]
[[0 0 0 0]
 [0 1 0 0]
 [1 0 0 1]]
[[b'-0.24094334367597509' b'-0.5287743603154729' b'0.4389353058377898'
  b'-0.8617590769357464']
 [b'-0.23491261870814903' b'1.091300857602473' b'0.9552957806407529'
  b'0.31839879816410843']
 [b'1.6700394174131683' b'0.5352194912233513' b'0.23103259500997717'
  b'1.6006969258048012']]


### Exercício 6

In [7]:
#Crie um ndarray com 100 números aleatórios
random_arr = np.random.randn(100)
#Acesse o 32º elemento
print(random_arr[31])
#Altere os índices de 18 a 32 para 128
random_arr[18:32] = 128
#Copie o ndarray para um novo ndarray
random_arr2 = random_arr.copy()
#Exiba o primeiro ndarray
print(random_arr)
print(random_arr[18:32])
#Altere o segundo ndarray modificando os índices de 18 a 32 para 256
random_arr2[18:32] = 256
#Exiba o segundo ndarray
print(random_arr2)
print(random_arr2[18:32])

0.5636373557169412
[ 1.44373207e+00  4.33682660e-01 -1.88245807e-01  3.06884990e-01
  7.10528023e-01 -7.00546258e-01 -6.36555414e-01 -3.60775167e-01
 -8.44677362e-01  3.14214434e-01 -6.16486395e-01 -1.04837773e+00
 -2.63711158e-01  5.35682167e-01 -1.80086555e+00 -4.97155577e-01
 -1.37428749e+00  5.52588589e-01  1.28000000e+02  1.28000000e+02
  1.28000000e+02  1.28000000e+02  1.28000000e+02  1.28000000e+02
  1.28000000e+02  1.28000000e+02  1.28000000e+02  1.28000000e+02
  1.28000000e+02  1.28000000e+02  1.28000000e+02  1.28000000e+02
 -1.37656051e+00  1.87526088e-01  1.54263653e+00  8.22998959e-01
 -1.56583344e+00  4.31440029e-01 -2.64843659e-01 -8.19117165e-01
 -4.99716835e-02  5.96227552e-02  2.63077888e-02  1.12287004e+00
 -8.09034751e-01 -4.86058582e-01  5.32285698e-01 -4.49596776e-01
  2.12087366e-01 -8.32609696e-01 -1.27033050e-01  9.68651412e-01
 -1.20086238e+00  2.13880946e-01 -1.73848812e+00 -8.85489062e-01
  1.55073581e+00  5.02775715e-01 -3.31010315e-02  4.27105537e-01
  1.61

### Exercício 7

In [8]:
#Crie a matriz abaixo
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
#Selecione através dos índices os itens 5, 6 e 7
print(arr2d[1,:-1])
#Selecione através dos índices os itens 7, 11 e 15
print(arr2d[1:,2])

[5 6 7]
[ 7 11 15]


### Exercício 8

In [9]:
#Crie uma lista com os nomes: Antônio, Carlos, Carlos, Antônio, José, Alfredo, Alfredo, Antônio
nomes = np.array(["Antônio", "Carlos", "Carlos", "Antônio", "José", "Alfredo", "Alfredo", "Antônio"])

#Crie uma lista chamada dívidas com os seguintes valores: 1000., 500., 0, 1640, 18399.99, 42640.18, 70., 84.90
dividas = np.array([1000., 500., 0, 1640, 18399.99, 42640.18, 70., 84.90])

#Busque na lista de nomes as ocorrências de Antônio e exiba suas dívidas
condicao = nomes == "Antônio"
print("Dividas do Antônio: ", dividas[condicao])

#Busque na lista de nomes as ocorrências de José e exiba suas dívidas
condicao = nomes == "José"
print("Dividas do José: ", dividas[condicao])

#Exiba as dívidas das pessoas diferente de Antônio e José
condicao = (nomes != "Antônio") & (nomes != "José")
print("Dividas dos Outros: ", dividas[condicao])

#Exiba os nomes das pessoas que possuem dívidas igual a 0 (zero)
condicao = dividas > 0
print("Pessoas com dívidas: ", nomes[condicao])

#Exiba os nomes das pessoas que possuem dívidas maior que 10000 (dez mil)
condicao = dividas > 10000
print("Pessoas com dívidas maior que R$10.000,00: ", nomes[condicao])

#Exiba os nomes das pessoas que possuem dívidas menores que 100 (cem) e maior do que 0 (zero)
condicao = (dividas < 100) & (dividas > 0)
print("Pessoas com dívidas entre R$1,00 e R$99,99: ", nomes[condicao])

Dividas do Antônio:  [1000.  1640.    84.9]
Dividas do José:  [18399.99]
Dividas dos Outros:  [  500.       0.   42640.18    70.  ]
Pessoas com dívidas:  ['Antônio' 'Carlos' 'Antônio' 'José' 'Alfredo' 'Alfredo' 'Antônio']
Pessoas com dívidas maior que R$10.000,00:  ['José' 'Alfredo']
Pessoas com dívidas entre R$1,00 e R$99,99:  ['Alfredo' 'Antônio']


### Exercício 9

In [10]:
#Ordene e exiba a lista de nomes criado no execício anterior
nomes.sort()
print(nomes)

#Ordene em ordem decrescente e exiba a lista de valores criado no execício anterior
dividas_ord = -np.sort(-dividas)
print(dividas)
print(dividas_ord)

['Alfredo' 'Alfredo' 'Antônio' 'Antônio' 'Antônio' 'Carlos' 'Carlos'
 'José']
[ 1000.     500.       0.    1640.   18399.99 42640.18    70.      84.9 ]
[42640.18 18399.99  1640.    1000.     500.      84.9     70.       0.  ]


### Exercício 10

In [11]:
#Exiba os valores únicos das listas criadas no exercício 8
print(np.unique(nomes))
print(np.unique(dividas))

['Alfredo' 'Antônio' 'Carlos' 'José']
[    0.      70.      84.9    500.    1000.    1640.   18399.99 42640.18]


## Extra

In [12]:
#Calculando a média, mediana e desvio padrão
#Recuperando a informação da Web
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

#Separando apenas a coluna do sépala
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print("%.2f" % mu, "%.2f" % med, "%.2f" % sd)

OSError: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data not found.

In [ ]:
#Encontrando a correlação entre duas colunas
#Recuperando todos os atributos da Iris
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]